export const UI = {
  STATE_RESET_HANDLER: 'UI.STATE_RESET_HANDLER',
  REPO_URL_HANLDER: 'UI.REPO_URL_HANLDER',
  CHANGE_PAGE_HANDLER: 'UI.CHANGE_PAGE_HANLDER',
  ISSUE_FILTER_HANDLER: 'UI.ISSUE_FILTER_HANDLER',
  ERROR_HANDLER: 'UI.ERROR_HANDLER',
  LOADING_HANDLER: 'UI.LOADING_HANDLER',
  CHANGE_PAGE_NUMBER_HANDLER: 'UI.CHANGE_PAGE_NUMBER_HANDLER'
}

export const DATA = {
  STATE_RESET_HANDLER: 'DATA.STATE_RESET_HANDLER',
  GIT_ISSUES_DATA_HANDLER: 'DATA.GIT_ISSUES_DATA_HANDLER'
}